# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: linxiaoyi6                  # 阿里云 login username
  namespace: linxiaoyi                              # 阿里云 命名空间
  imageName: mediahub-vue                        # 阿里云 仓库名称
  registry: registry.cn-hangzhou.aliyuncs.com   # 阿里云 公网地址
  dockerfilepath:  /Dockerfile       # Github Dockerfile相对路径

steps:
- script: |
    npm install
    npm run build
    docker build -f $(dockerfilepath) -t $(imageName) .
    docker login -u $(dockerId) -p $(pwd) $(registry)
    docker tag $(imageName) $(registry)/$(namespace)/$(imageName)
    docker push $(registry)/$(namespace)/$(imageName)
  displayName: 'npm install and build'
